title: A CandyPink Blog
email: candypink@outlook.it

github_username:  candypink

# Build settings
markdown: kramdown

remote_theme: candypink/jekyll-theme-candypink

plugins:
 - jekyll-feed
 - jekyll-seo-tag

navigation:
  - name: Blog
    link: https://candypink.github.io/blog.html
  - name: Portfolio
    link: https://candypink.github.io/portfolio.html
  - name: About
    link: https://candypink.github.io/about.html
