title: A CandyPink Blog
email: candypink@outlook.it

github_username:  candypink

# Build settings
markdown: kramdown

remote_theme: candypink/jekyll-theme-candypink

plugins:
 - jekyll-feed
 - jekyll-seo-tag
